import { CommandMetadata } from '../registry/command-types.js';

export interface CatalogEntry extends CommandMetadata {
  id: string;
}

export const PRD_CATALOG: CatalogEntry[] = [
  // 7.1. Fitur Grup, Moderasi & Keamanan (F001-F010)
  {
    id: 'F001',
    name: 'antiflood',
    aliases: ['f001'],
    category: 'admin',
    plugin: 'moderation',
    featureFlag: 'group_moderation',
    minRole: 'admin',
    description: 'Anti-flood adaptif: Mendeteksi lonjakan pesan per user/grup.',
    usage: '/antiflood',
    examples: ['/antiflood']
  },
  {
    id: 'F002',
    name: 'antilinkwhitelist',
    aliases: ['f002'],
    category: 'admin',
    plugin: 'moderation',
    featureFlag: 'group_moderation',
    minRole: 'admin',
    description: 'Anti-link whitelist bertingkat: Whitelist domain global/per grup.',
    usage: '/antilinkwhitelist',
    examples: ['/antilinkwhitelist']
  },
  {
    id: 'F003',
    name: 'antiforward',
    aliases: ['f003'],
    category: 'admin',
    plugin: 'moderation',
    featureFlag: 'group_moderation',
    minRole: 'admin',
    description: 'Anti-forward spam: Mendeteksi pesan forwarded berulang.',
    usage: '/antiforward',
    examples: ['/antiforward']
  },
  {
    id: 'F004',
    name: 'antijoin',
    aliases: ['f004', 'antijoinbot'],
    category: 'admin',
    plugin: 'moderation',
    featureFlag: 'group_moderation',
    minRole: 'admin',
    description: 'Anti-join bot/akun baru: Memberi skor risiko ke member baru.',
    usage: '/antijoin',
    examples: ['/antijoin']
  },
  {
    id: 'F005',
    name: 'captcha2',
    aliases: ['f005'],
    category: 'admin',
    plugin: 'moderation',
    featureFlag: 'group_moderation',
    minRole: 'admin',
    description: 'Captcha mode bertingkat: Captcha angka, pilihan ganda, atau kata acak.',
    usage: '/captcha2',
    examples: ['/captcha2']
  },
  {
    id: 'F006',
    name: 'muteprogressive',
    aliases: ['f006'],
    category: 'admin',
    plugin: 'moderation',
    featureFlag: 'group_moderation',
    minRole: 'admin',
    description: 'Mute bertahap: Pelanggaran bertingkat (delete, mute, kick).',
    usage: '/muteprogressive',
    examples: ['/muteprogressive']
  },
  {
    id: 'F007',
    name: 'lockdownschedule',
    aliases: ['f007'],
    category: 'admin',
    plugin: 'moderation',
    featureFlag: 'group_moderation',
    minRole: 'admin',
    description: 'Auto-lockdown schedule: Mengunci grup otomatis pada jam tertentu.',
    usage: '/lockdownschedule',
    examples: ['/lockdownschedule']
  },
  {
    id: 'F008',
    name: 'antitagall',
    aliases: ['f008'],
    category: 'admin',
    plugin: 'moderation',
    featureFlag: 'group_moderation',
    minRole: 'admin',
    description: 'Anti-tag-all berlebihan: Membatasi mention massal.',
    usage: '/antitagall',
    examples: ['/antitagall']
  },
  {
    id: 'F009',
    name: 'moderationappeal',
    aliases: ['f009', 'appeal'],
    category: 'admin',
    plugin: 'moderation',
    featureFlag: 'group_moderation',
    minRole: 'user',
    description: 'Moderation appeal: Mengajukan banding pelanggaran ke admin.',
    usage: '/moderationappeal',
    examples: ['/moderationappeal']
  },
  {
    id: 'F010',
    name: 'safetydigest',
    aliases: ['f010'],
    category: 'admin',
    plugin: 'moderation',
    featureFlag: 'group_moderation',
    minRole: 'admin',
    description: 'Safety digest harian: Ringkasan pelanggaran dan user berisiko.',
    usage: '/safetydigest',
    examples: ['/safetydigest']
  },

  // 7.2. Privasi, Data & Kepatuhan (F011-F020)
  {
    id: 'F011',
    name: 'retentionmode',
    aliases: ['f011'],
    category: 'general',
    plugin: 'privacy',
    featureFlag: 'privacy',
    minRole: 'admin',
    description: 'Mode retensi per fitur: Retensi data berbeda untuk game/log.',
    usage: '/retentionmode',
    examples: ['/retentionmode']
  },
  {
    id: 'F012',
    name: 'exportdata',
    aliases: ['f012'],
    category: 'general',
    plugin: 'privacy',
    featureFlag: 'privacy',
    minRole: 'user',
    description: 'Export data user: Meminta ringkasan data yang tersimpan.',
    usage: '/exportdata',
    examples: ['/exportdata']
  },
  {
    id: 'F013',
    name: 'deletedata',
    aliases: ['f013'],
    category: 'general',
    plugin: 'privacy',
    featureFlag: 'privacy',
    minRole: 'user',
    description: 'Delete my data: Menghapus data personal sesuai policy.',
    usage: '/deletedata',
    examples: ['/deletedata']
  },
  {
    id: 'F014',
    name: 'anonanalytics',
    aliases: ['f014'],
    category: 'general',
    plugin: 'privacy',
    featureFlag: 'privacy',
    minRole: 'admin',
    description: 'Anonim analytics: Menampilkan statistik tanpa JID asli.',
    usage: '/anonanalytics',
    examples: ['/anonanalytics']
  },
  {
    id: 'F015',
    name: 'sensitivelog',
    aliases: ['f015'],
    category: 'general',
    plugin: 'privacy',
    featureFlag: 'privacy',
    minRole: 'owner',
    description: 'Sensitive log redaction: Menyamarkan nomor/token/URL privat dari log.',
    usage: '/sensitivelog',
    examples: ['/sensitivelog']
  },
  {
    id: 'F016',
    name: 'consentai',
    aliases: ['f016'],
    category: 'general',
    plugin: 'privacy',
    featureFlag: 'privacy',
    minRole: 'user',
    description: 'Consent per fitur AI: Persetujuan pengiriman konten ke AI.',
    usage: '/consentai',
    examples: ['/consentai']
  },
  {
    id: 'F017',
    name: 'dataclassification',
    aliases: ['f017'],
    category: 'general',
    plugin: 'privacy',
    featureFlag: 'privacy',
    minRole: 'admin',
    description: 'Data classification: Memberi label data (public/personal/sensitive).',
    usage: '/dataclassification',
    examples: ['/dataclassification']
  },
  {
    id: 'F018',
    name: 'privateguard',
    aliases: ['f018'],
    category: 'general',
    plugin: 'privacy',
    featureFlag: 'privacy',
    minRole: 'user',
    description: 'Private command guard: Batasan penggunaan di chat pribadi.',
    usage: '/privateguard',
    examples: ['/privateguard']
  },
  {
    id: 'F019',
    name: 'privacynotice',
    aliases: ['f019'],
    category: 'general',
    plugin: 'privacy',
    featureFlag: 'privacy',
    minRole: 'admin',
    description: 'Admin privacy notice: Penjelasan singkat fitur sensitif.',
    usage: '/privacynotice',
    examples: ['/privacynotice']
  },
  {
    id: 'F020',
    name: 'auditaccess',
    aliases: ['f020'],
    category: 'general',
    plugin: 'privacy',
    featureFlag: 'privacy',
    minRole: 'owner',
    description: 'Audit access viewer: Viewer akses data/fitur sensitif.',
    usage: '/auditaccess',
    examples: ['/auditaccess']
  },

  // 7.3. Admin, Owner & Operasional (F021-F030)
  {
    id: 'F021',
    name: 'setupwizard',
    aliases: ['f021'],
    category: 'admin',
    plugin: 'admin',
    featureFlag: 'admin',
    minRole: 'admin',
    description: 'Setup wizard v2: Wizard onboarding grup dengan preset.',
    usage: '/setupwizard',
    examples: ['/setupwizard']
  },
  {
    id: 'F022',
    name: 'presetfitur',
    aliases: ['f022'],
    category: 'admin',
    plugin: 'admin',
    featureFlag: 'admin',
    minRole: 'admin',
    description: 'Preset fitur grup: Menerapkan bundle fitur tertentu.',
    usage: '/presetfitur',
    examples: ['/presetfitur']
  },
  {
    id: 'F023',
    name: 'rolecustom',
    aliases: ['f023'],
    category: 'admin',
    plugin: 'admin',
    featureFlag: 'admin',
    minRole: 'admin',
    description: 'Role custom: Membuat role custom dengan izin command tertentu.',
    usage: '/rolecustom',
    examples: ['/rolecustom']
  },
  {
    id: 'F024',
    name: 'delegatedmod',
    aliases: ['f024'],
    category: 'admin',
    plugin: 'admin',
    featureFlag: 'admin',
    minRole: 'admin',
    description: 'Delegated moderator: Menunjuk moderator terbatas.',
    usage: '/delegatedmod',
    examples: ['/delegatedmod']
  },
  {
    id: 'F025',
    name: 'configdiff',
    aliases: ['f025'],
    category: 'admin',
    plugin: 'admin',
    featureFlag: 'admin',
    minRole: 'admin',
    description: 'Config diff: Menampilkan perubahan konfigurasi grup.',
    usage: '/configdiff',
    examples: ['/configdiff']
  },
  {
    id: 'F026',
    name: 'rollbackconfig',
    aliases: ['f026'],
    category: 'admin',
    plugin: 'admin',
    featureFlag: 'admin',
    minRole: 'admin',
    description: 'Rollback config: Mengembalikan konfigurasi grup ke versi sebelumnya.',
    usage: '/rollbackconfig',
    examples: ['/rollbackconfig']
  },
  {
    id: 'F027',
    name: 'policyeditor',
    aliases: ['f027'],
    category: 'admin',
    plugin: 'admin',
    featureFlag: 'admin',
    minRole: 'admin',
    description: 'Command policy editor: Atur izin command per role/jam.',
    usage: '/policyeditor',
    examples: ['/policyeditor']
  },
  {
    id: 'F028',
    name: 'ownertaskqueue',
    aliases: ['f028'],
    category: 'owner',
    plugin: 'admin',
    featureFlag: 'admin',
    minRole: 'owner',
    description: 'Owner task queue: Daftar konfirmasi sewa, error, dan banding.',
    usage: '/ownertaskqueue',
    examples: ['/ownertaskqueue']
  },
  {
    id: 'F029',
    name: 'announcementbuilder',
    aliases: ['f029'],
    category: 'admin',
    plugin: 'admin',
    featureFlag: 'admin',
    minRole: 'admin',
    description: 'Admin announcement builder: Template pengumuman terjadwal.',
    usage: '/announcementbuilder',
    examples: ['/announcementbuilder']
  },
  {
    id: 'F030',
    name: 'grouphealth',
    aliases: ['f030'],
    category: 'admin',
    plugin: 'admin',
    featureFlag: 'admin',
    minRole: 'admin',
    description: 'Group health score: Skor kesehatan grup berdasarkan keaktifan.',
    usage: '/grouphealth',
    examples: ['/grouphealth']
  },

  // 7.4. Komunitas, Sekolah & Kolaborasi (F031-F040)
  {
    id: 'F031',
    name: 'jadwalpelajaran',
    aliases: ['f031'],
    category: 'school',
    plugin: 'school',
    featureFlag: 'school',
    minRole: 'user',
    description: 'Jadwal pelajaran interaktif: Simpan dan ingatkan jadwal pelajaran.',
    usage: '/jadwalpelajaran',
    examples: ['/jadwalpelajaran']
  },
  {
    id: 'F032',
    name: 'tugaskelas',
    aliases: ['f032'],
    category: 'school',
    plugin: 'school',
    featureFlag: 'school',
    minRole: 'user',
    description: 'Tugas kelas: Buat, daftar, dan ingatkan deadline tugas.',
    usage: '/tugaskelas',
    examples: ['/tugaskelas']
  },
  {
    id: 'F033',
    name: 'absensiqr',
    aliases: ['f033'],
    category: 'school',
    plugin: 'school',
    featureFlag: 'school',
    minRole: 'user',
    description: 'Absensi QR: Absensi dengan QR token dinamis.',
    usage: '/absensiqr',
    examples: ['/absensiqr']
  },
  {
    id: 'F034',
    name: 'piketkelas',
    aliases: ['f034'],
    category: 'school',
    plugin: 'school',
    featureFlag: 'school',
    minRole: 'user',
    description: 'Piket kelas: Jadwal piket mingguan dengan reminder otomatis.',
    usage: '/piketkelas',
    examples: ['/piketkelas']
  },
  {
    id: 'F035',
    name: 'bankmateri',
    aliases: ['f035'],
    category: 'school',
    plugin: 'school',
    featureFlag: 'school',
    minRole: 'user',
    description: 'Bank materi: Simpan link/file materi dengan pencarian cepat.',
    usage: '/bankmateri',
    examples: ['/bankmateri']
  },
  {
    id: 'F036',
    name: 'kuiskelas',
    aliases: ['f036'],
    category: 'school',
    plugin: 'school',
    featureFlag: 'school',
    minRole: 'user',
    description: 'Kuis kelas terjadwal: Kuis otomatis harian/mingguan kelas.',
    usage: '/kuiskelas',
    examples: ['/kuiskelas']
  },
  {
    id: 'F037',
    name: 'catatanrapat',
    aliases: ['f037'],
    category: 'school',
    plugin: 'school',
    featureFlag: 'school',
    minRole: 'user',
    description: 'Catatan rapat komunitas: Buat notulen singkat dan action item.',
    usage: '/catatanrapat',
    examples: ['/catatanrapat']
  },
  {
    id: 'F038',
    name: 'votingkeputusan',
    aliases: ['f038'],
    category: 'school',
    plugin: 'school',
    featureFlag: 'school',
    minRole: 'user',
    description: 'Voting keputusan: Polling dengan quorum dan deadline.',
    usage: '/votingkeputusan',
    examples: ['/votingkeputusan']
  },
  {
    id: 'F039',
    name: 'birthday',
    aliases: ['f039'],
    category: 'school',
    plugin: 'school',
    featureFlag: 'school',
    minRole: 'user',
    description: 'Birthday & anniversary: Kartu ucapan ulang tahun member.',
    usage: '/birthday',
    examples: ['/birthday']
  },
  {
    id: 'F040',
    name: 'reputasipositif',
    aliases: ['f040'],
    category: 'school',
    plugin: 'school',
    featureFlag: 'school',
    minRole: 'user',
    description: 'Reputasi positif: Sistem poin terima kasih dan kontribusi.',
    usage: '/reputasipositif',
    examples: ['/reputasipositif']
  },

  // 7.5. Produktivitas & Reminder (F041-F050)
  {
    id: 'F041',
    name: 'reminderulang',
    aliases: ['f041'],
    category: 'productivity',
    plugin: 'productivity',
    featureFlag: 'productivity',
    minRole: 'user',
    description: 'Reminder berulang: Pengingat harian/mingguan/Rrule.',
    usage: '/reminderulang',
    examples: ['/reminderulang']
  },
  {
    id: 'F042',
    name: 'remindernlp',
    aliases: ['f042'],
    category: 'productivity',
    plugin: 'productivity',
    featureFlag: 'productivity',
    minRole: 'user',
    description: 'Reminder natural language: Pengingat lewat bahasa alami.',
    usage: '/remindernlp',
    examples: ['/remindernlp']
  },
  {
    id: 'F043',
    name: 'checklistgrup',
    aliases: ['f043'],
    category: 'productivity',
    plugin: 'productivity',
    featureFlag: 'productivity',
    minRole: 'user',
    description: 'Checklist grup: Checklist bersama untuk event/tugas.',
    usage: '/checklistgrup',
    examples: ['/checklistgrup']
  },
  {
    id: 'F044',
    name: 'pomodorogrup',
    aliases: ['f044'],
    category: 'productivity',
    plugin: 'productivity',
    featureFlag: 'productivity',
    minRole: 'user',
    description: 'Pomodoro grup: Sesi fokus Pomodoro bersama.',
    usage: '/pomodorogrup',
    examples: ['/pomodorogrup']
  },
  {
    id: 'F045',
    name: 'agendaharian',
    aliases: ['f045'],
    category: 'productivity',
    plugin: 'productivity',
    featureFlag: 'productivity',
    minRole: 'user',
    description: 'Agenda harian: Mengirim agenda grup/pribadi di pagi hari.',
    usage: '/agendaharian',
    examples: ['/agendaharian']
  },
  {
    id: 'F046',
    name: 'followup',
    aliases: ['f046'],
    category: 'productivity',
    plugin: 'productivity',
    featureFlag: 'productivity',
    minRole: 'user',
    description: 'Follow-up otomatis: Mengingatkan chat yang belum dibalas.',
    usage: '/followup',
    examples: ['/followup']
  },
  {
    id: 'F047',
    name: 'quicknote',
    aliases: ['f047'],
    category: 'productivity',
    plugin: 'productivity',
    featureFlag: 'productivity',
    minRole: 'user',
    description: 'Quick note pribadi: Menyimpan catatan pribadi ber-tag.',
    usage: '/quicknote',
    examples: ['/quicknote']
  },
  {
    id: 'F048',
    name: 'kanbanmini',
    aliases: ['f048'],
    category: 'productivity',
    plugin: 'productivity',
    featureFlag: 'productivity',
    minRole: 'user',
    description: 'Kanban mini: Board tugas (To Do, Doing, Done).',
    usage: '/kanbanmini',
    examples: ['/kanbanmini']
  },
  {
    id: 'F049',
    name: 'meetingtimer',
    aliases: ['f049'],
    category: 'productivity',
    plugin: 'productivity',
    featureFlag: 'productivity',
    minRole: 'user',
    description: 'Meeting timer: Rapat ber-timebox dengan ringkasan.',
    usage: '/meetingtimer',
    examples: ['/meetingtimer']
  },
  {
    id: 'F050',
    name: 'deadlineheatmap',
    aliases: ['f050'],
    category: 'productivity',
    plugin: 'productivity',
    featureFlag: 'productivity',
    minRole: 'user',
    description: 'Deadline heatmap: Tampilan visual deadline terdekat.',
    usage: '/deadlineheatmap',
    examples: ['/deadlineheatmap']
  },

  // 7.6. Media, Stiker & Kreativitas (F051-F060)
  {
    id: 'F051',
    name: 'stickerpackmanager',
    aliases: ['f051'],
    category: 'sticker',
    plugin: 'media',
    featureFlag: 'media',
    minRole: 'user',
    description: 'Sticker pack manager: Mengelola pack dan metadata stiker.',
    usage: '/stickerpackmanager',
    examples: ['/stickerpackmanager']
  },
  {
    id: 'F052',
    name: 'stickertemplate',
    aliases: ['f052'],
    category: 'sticker',
    plugin: 'media',
    featureFlag: 'media',
    minRole: 'user',
    description: 'Sticker template editor: Template teks/meme stiker.',
    usage: '/stickertemplate',
    examples: ['/stickertemplate']
  },
  {
    id: 'F053',
    name: 'autocaption',
    aliases: ['f053'],
    category: 'media',
    plugin: 'media',
    featureFlag: 'media',
    minRole: 'user',
    description: 'Auto-caption media lokal: Caption otomatis via OCR lokal.',
    usage: '/autocaption',
    examples: ['/autocaption']
  },
  {
    id: 'F054',
    name: 'watermarkpolicy',
    aliases: ['f054'],
    category: 'media',
    plugin: 'media',
    featureFlag: 'media',
    minRole: 'admin',
    description: 'Watermark policy: Menentukan watermark otomatis per grup.',
    usage: '/watermarkpolicy',
    examples: ['/watermarkpolicy']
  },
  {
    id: 'F055',
    name: 'mediabatch',
    aliases: ['f055'],
    category: 'media',
    plugin: 'media',
    featureFlag: 'media',
    minRole: 'user',
    description: 'Media batch pipeline: Kompresi/watermark media sekaligus.',
    usage: '/mediabatch',
    examples: ['/mediabatch']
  },
  {
    id: 'F056',
    name: 'avatarcard',
    aliases: ['f056'],
    category: 'media',
    plugin: 'media',
    featureFlag: 'media',
    minRole: 'user',
    description: 'Avatar card: Membuat kartu profil visual pengguna.',
    usage: '/avatarcard',
    examples: ['/avatarcard']
  },
  {
    id: 'F057',
    name: 'quotecard',
    aliases: ['f057'],
    category: 'media',
    plugin: 'media',
    featureFlag: 'media',
    minRole: 'user',
    description: 'Quote card v2: Quote visual estetik dari pesan chat.',
    usage: '/quotecard',
    examples: ['/quotecard']
  },
  {
    id: 'F058',
    name: 'memechallenge',
    aliases: ['f058'],
    category: 'media',
    plugin: 'media',
    featureFlag: 'media',
    minRole: 'user',
    description: 'Meme challenge: Mengelola lomba meme di grup.',
    usage: '/memechallenge',
    examples: ['/memechallenge']
  },
  {
    id: 'F059',
    name: 'mediapreview',
    aliases: ['f059'],
    category: 'media',
    plugin: 'media',
    featureFlag: 'media',
    minRole: 'user',
    description: 'Media safety preview: Informasi ukuran dan risiko file.',
    usage: '/mediapreview',
    examples: ['/mediapreview']
  },
  {
    id: 'F060',
    name: 'postergroup',
    aliases: ['f060'],
    category: 'media',
    plugin: 'media',
    featureFlag: 'media',
    minRole: 'user',
    description: 'Template poster grup: Poster sederhana via command.',
    usage: '/postergroup',
    examples: ['/postergroup']
  },

  // 7.7. Dokumen, File & Utility (F061-F070)
  {
    id: 'F061',
    name: 'pdfsplit',
    aliases: ['f061'],
    category: 'document',
    plugin: 'document',
    featureFlag: 'document',
    minRole: 'user',
    description: 'PDF split: Memisahkan halaman dokumen PDF.',
    usage: '/pdfsplit',
    examples: ['/pdfsplit']
  },
  {
    id: 'F062',
    name: 'pdfreorder',
    aliases: ['f062'],
    category: 'document',
    plugin: 'document',
    featureFlag: 'document',
    minRole: 'user',
    description: 'PDF reorder: Mengubah urutan halaman PDF.',
    usage: '/pdfreorder',
    examples: ['/pdfreorder']
  },
  {
    id: 'F063',
    name: 'pdfprotect',
    aliases: ['f063'],
    category: 'document',
    plugin: 'document',
    featureFlag: 'document',
    minRole: 'user',
    description: 'PDF protect: Melindungi dokumen PDF dengan password.',
    usage: '/pdfprotect',
    examples: ['/pdfprotect']
  },
  {
    id: 'F064',
    name: 'pdfunlock',
    aliases: ['f064'],
    category: 'document',
    plugin: 'document',
    featureFlag: 'document',
    minRole: 'user',
    description: 'PDF unlock notice: Panduan membuka file PDF terkunci.',
    usage: '/pdfunlock',
    examples: ['/pdfunlock']
  },
  {
    id: 'F065',
    name: 'ocrbatch',
    aliases: ['f065'],
    category: 'document',
    plugin: 'document',
    featureFlag: 'document',
    minRole: 'user',
    description: 'Image OCR batch: OCR banyak gambar ke satu file teks.',
    usage: '/ocrbatch',
    examples: ['/ocrbatch']
  },
  {
    id: 'F066',
    name: 'docsummary',
    aliases: ['f066'],
    category: 'document',
    plugin: 'document',
    featureFlag: 'document',
    minRole: 'user',
    description: 'Doc summary: Ringkasan dokumen dengan batasan privasi.',
    usage: '/docsummary',
    examples: ['/docsummary']
  },
  {
    id: 'F067',
    name: 'filerename',
    aliases: ['f067'],
    category: 'document',
    plugin: 'document',
    featureFlag: 'document',
    minRole: 'user',
    description: 'File rename helper: Rename file kiriman dengan pola.',
    usage: '/filerename',
    examples: ['/filerename']
  },
  {
    id: 'F068',
    name: 'zipsafepreview',
    aliases: ['f068'],
    category: 'document',
    plugin: 'document',
    featureFlag: 'document',
    minRole: 'user',
    description: 'ZIP safe preview: Preview isi file ZIP/RAR.',
    usage: '/zipsafepreview',
    examples: ['/zipsafepreview']
  },
  {
    id: 'F069',
    name: 'qratttendance',
    aliases: ['f069'],
    category: 'document',
    plugin: 'document',
    featureFlag: 'document',
    minRole: 'admin',
    description: 'QR attendance generator: Membuat QR absensi berwaktu.',
    usage: '/qratttendance',
    examples: ['/qratttendance']
  },
  {
    id: 'F070',
    name: 'unitconverter',
    aliases: ['f070'],
    category: 'document',
    plugin: 'document',
    featureFlag: 'document',
    minRole: 'user',
    description: 'Unit converter lengkap: Konversi satuan dan mata uang.',
    usage: '/unitconverter',
    examples: ['/unitconverter']
  },

  // 7.8. AI, Edukasi & Bahasa (F071-F080)
  {
    id: 'F071',
    name: 'tutorpelajaran',
    aliases: ['f071'],
    category: 'text',
    plugin: 'ai',
    featureFlag: 'ai',
    minRole: 'user',
    description: 'Tutor pelajaran: Mode asisten belajar interaktif.',
    usage: '/tutorpelajaran',
    examples: ['/tutorpelajaran']
  },
  {
    id: 'F072',
    name: 'latihansoal',
    aliases: ['f072'],
    category: 'text',
    plugin: 'ai',
    featureFlag: 'ai',
    minRole: 'user',
    description: 'Latihan soal adaptif: Latihan soal dengan tingkat kesulitan.',
    usage: '/latihansoal',
    examples: ['/latihansoal']
  },
  {
    id: 'F073',
    name: 'rubrikpenilaian',
    aliases: ['f073'],
    category: 'text',
    plugin: 'ai',
    featureFlag: 'ai',
    minRole: 'admin',
    description: 'Rubrik penilaian: Membuat kriteria penilaian tugas/essay.',
    usage: '/rubrikpenilaian',
    examples: ['/rubrikpenilaian']
  },
  {
    id: 'F074',
    name: 'flashcard',
    aliases: ['f074'],
    category: 'text',
    plugin: 'ai',
    featureFlag: 'ai',
    minRole: 'user',
    description: 'Flashcard spaced repetition: Kartu belajar berkala.',
    usage: '/flashcard',
    examples: ['/flashcard']
  },
  {
    id: 'F075',
    name: 'debatsehat',
    aliases: ['f075'],
    category: 'text',
    plugin: 'ai',
    featureFlag: 'ai',
    minRole: 'user',
    description: 'Mode debat sehat: Mengatur giliran debat dan ringkasan.',
    usage: '/debatsehat',
    examples: ['/debatsehat']
  },
  {
    id: 'F076',
    name: 'parafrase',
    aliases: ['f076'],
    category: 'text',
    plugin: 'ai',
    featureFlag: 'ai',
    minRole: 'user',
    description: 'Parafrase multi gaya: Mengubah gaya penulisan teks.',
    usage: '/parafrase',
    examples: ['/parafrase']
  },
  {
    id: 'F077',
    name: 'koreksibahasa',
    aliases: ['f077'],
    category: 'text',
    plugin: 'ai',
    featureFlag: 'ai',
    minRole: 'user',
    description: 'Koreksi bahasa Indonesia: Memperbaiki ejaan dan typo.',
    usage: '/koreksibahasa',
    examples: ['/koreksibahasa']
  },
  {
    id: 'F078',
    name: 'vocabbuilder',
    aliases: ['f078'],
    category: 'text',
    plugin: 'ai',
    featureFlag: 'ai',
    minRole: 'user',
    description: 'Vocabulary builder: Kosakata harian dan kuis kilat.',
    usage: '/vocabbuilder',
    examples: ['/vocabbuilder']
  },
  {
    id: 'F079',
    name: 'eli5',
    aliases: ['f079'],
    category: 'text',
    plugin: 'ai',
    featureFlag: 'ai',
    minRole: 'user',
    description: 'Explain like I am 5/15/expert: Penjelasan berlevel.',
    usage: '/eli5',
    examples: ['/eli5']
  },
  {
    id: 'F080',
    name: 'aisafetybudget',
    aliases: ['f080'],
    category: 'text',
    plugin: 'ai',
    featureFlag: 'ai',
    minRole: 'admin',
    description: 'AI safety budget: Limit token/biaya AI per grup.',
    usage: '/aisafetybudget',
    examples: ['/aisafetybudget']
  },

  // 7.9. Bisnis, UMKM & Keuangan Simulasi (F081-F090)
  {
    id: 'F081',
    name: 'katalogproduk',
    aliases: ['f081'],
    category: 'business',
    plugin: 'business',
    featureFlag: 'business',
    minRole: 'user',
    description: 'Katalog produk grup: Daftar produk, harga, dan kategori.',
    usage: '/katalogproduk',
    examples: ['/katalogproduk']
  },
  {
    id: 'F082',
    name: 'orderform',
    aliases: ['f082'],
    category: 'business',
    plugin: 'business',
    featureFlag: 'business',
    minRole: 'user',
    description: 'Order form WA: Form pemesanan dengan ID order.',
    usage: '/orderform',
    examples: ['/orderform']
  },
  {
    id: 'F083',
    name: 'invoiceteks',
    aliases: ['f083'],
    category: 'business',
    plugin: 'business',
    featureFlag: 'business',
    minRole: 'user',
    description: 'Invoice teks: Membuat invoice berformat WhatsApp.',
    usage: '/invoiceteks',
    examples: ['/invoiceteks']
  },
  {
    id: 'F084',
    name: 'stokreminder',
    aliases: ['f084'],
    category: 'business',
    plugin: 'business',
    featureFlag: 'business',
    minRole: 'admin',
    description: 'Stok reminder: Peringatan stok produk menipis.',
    usage: '/stokreminder',
    examples: ['/stokreminder']
  },
  {
    id: 'F085',
    name: 'customernote',
    aliases: ['f085'],
    category: 'business',
    plugin: 'business',
    featureFlag: 'business',
    minRole: 'admin',
    description: 'Customer note: Catatan pelanggan untuk grup jualan.',
    usage: '/customernote',
    examples: ['/customernote']
  },
  {
    id: 'F086',
    name: 'promoscheduler',
    aliases: ['f086'],
    category: 'business',
    plugin: 'business',
    featureFlag: 'business',
    minRole: 'admin',
    description: 'Promo scheduler: Penjadwalan broadcast promo.',
    usage: '/promoscheduler',
    examples: ['/promoscheduler']
  },
  {
    id: 'F087',
    name: 'kassederhana',
    aliases: ['f087'],
    category: 'business',
    plugin: 'business',
    featureFlag: 'business',
    minRole: 'user',
    description: 'Kas sederhana: Catat kas kelompok atau kelas.',
    usage: '/kassederhana',
    examples: ['/kassederhana']
  },
  {
    id: 'F088',
    name: 'splitbill',
    aliases: ['f088'],
    category: 'business',
    plugin: 'business',
    featureFlag: 'business',
    minRole: 'user',
    description: 'Split bill: Pembagian dan pelacakan tagihan kelompok.',
    usage: '/splitbill',
    examples: ['/splitbill']
  },
  {
    id: 'F089',
    name: 'budgetchallenge',
    aliases: ['f089'],
    category: 'business',
    plugin: 'business',
    featureFlag: 'business',
    minRole: 'user',
    description: 'Budget challenge: Kompetisi hemat mingguan.',
    usage: '/budgetchallenge',
    examples: ['/budgetchallenge']
  },
  {
    id: 'F090',
    name: 'simulasiinvestasi',
    aliases: ['f090'],
    category: 'business',
    plugin: 'business',
    featureFlag: 'business',
    minRole: 'user',
    description: 'Simulasi investasi: Game edukasi finansial fiktif.',
    usage: '/simulasiinvestasi',
    examples: ['/simulasiinvestasi']
  },

  // 7.10. Downloader, Link & Web Utility (F091-F100)
  {
    id: 'F091',
    name: 'linkreputation',
    aliases: ['f091'],
    category: 'downloader',
    plugin: 'downloader',
    featureFlag: 'downloader',
    minRole: 'user',
    description: 'Link reputation: Analisis reputasi URL/domain.',
    usage: '/linkreputation',
    examples: ['/linkreputation']
  },
  {
    id: 'F092',
    name: 'urlexpander',
    aliases: ['f092'],
    category: 'downloader',
    plugin: 'downloader',
    featureFlag: 'downloader',
    minRole: 'user',
    description: 'URL expander: Membuka shortlink dengan aman.',
    usage: '/urlexpander',
    examples: ['/urlexpander']
  },
  {
    id: 'F093',
    name: 'screenshotweb',
    aliases: ['f093'],
    category: 'downloader',
    plugin: 'downloader',
    featureFlag: 'downloader',
    minRole: 'user',
    description: 'Screenshot website: Ambil gambar halaman publik.',
    usage: '/screenshotweb',
    examples: ['/screenshotweb']
  },
  {
    id: 'F094',
    name: 'bookmarkgrup',
    aliases: ['f094'],
    category: 'downloader',
    plugin: 'downloader',
    featureFlag: 'downloader',
    minRole: 'user',
    description: 'Bookmark grup: Simpan link penting grup dengan tag.',
    usage: '/bookmarkgrup',
    examples: ['/bookmarkgrup']
  },
  {
    id: 'F095',
    name: 'downloaderqueue',
    aliases: ['f095'],
    category: 'downloader',
    plugin: 'downloader',
    featureFlag: 'downloader',
    minRole: 'user',
    description: 'Downloader queue status: Cek urutan antrean download.',
    usage: '/downloaderqueue',
    examples: ['/downloaderqueue']
  },
  {
    id: 'F096',
    name: 'downloaderretry',
    aliases: ['f096'],
    category: 'downloader',
    plugin: 'downloader',
    featureFlag: 'downloader',
    minRole: 'user',
    description: 'Downloader retry user: Mencoba ulang proses download.',
    usage: '/downloaderretry',
    examples: ['/downloaderretry']
  },
  {
    id: 'F097',
    name: 'mediasource',
    aliases: ['f097'],
    category: 'downloader',
    plugin: 'downloader',
    featureFlag: 'downloader',
    minRole: 'user',
    description: 'Media source attribution: Menyertakan watermark sumber.',
    usage: '/mediasource',
    examples: ['/mediasource']
  },
  {
    id: 'F098',
    name: 'downloadquota',
    aliases: ['f098'],
    category: 'downloader',
    plugin: 'downloader',
    featureFlag: 'downloader',
    minRole: 'user',
    description: 'Download quota: Kuota download harian grup.',
    usage: '/downloadquota',
    examples: ['/downloadquota']
  },
  {
    id: 'F099',
    name: 'safedomain',
    aliases: ['f099'],
    category: 'downloader',
    plugin: 'downloader',
    featureFlag: 'downloader',
    minRole: 'user',
    description: 'Safe domain request: Meminta whitelist domain baru.',
    usage: '/safedomain',
    examples: ['/safedomain']
  },
  {
    id: 'F100',
    name: 'linkreminder',
    aliases: ['f100'],
    category: 'downloader',
    plugin: 'downloader',
    featureFlag: 'downloader',
    minRole: 'user',
    description: 'Link reminder: Set pengingat membaca link nanti.',
    usage: '/linkreminder',
    examples: ['/linkreminder']
  },

  // 7.11. Automasi, Integrasi & Webhook (F101-F110)
  {
    id: 'F101',
    name: 'webhookfilter',
    aliases: ['f101'],
    category: 'general',
    plugin: 'automation',
    featureFlag: 'automation',
    minRole: 'admin',
    description: 'Webhook event filter: Filter event webhook tertentu.',
    usage: '/webhookfilter',
    examples: ['/webhookfilter']
  },
  {
    id: 'F102',
    name: 'webhookretry',
    aliases: ['f102'],
    category: 'general',
    plugin: 'automation',
    featureFlag: 'automation',
    minRole: 'admin',
    description: 'Webhook retry queue: Antrean retry webhook gagal.',
    usage: '/webhookretry',
    examples: ['/webhookretry']
  },
  {
    id: 'F103',
    name: 'gcalbridge',
    aliases: ['f103'],
    category: 'general',
    plugin: 'automation',
    featureFlag: 'automation',
    minRole: 'admin',
    description: 'Google Calendar bridge: Sinkron event ke Google Calendar.',
    usage: '/gcalbridge',
    examples: ['/gcalbridge']
  },
  {
    id: 'F104',
    name: 'githubwatch',
    aliases: ['f104'],
    category: 'general',
    plugin: 'automation',
    featureFlag: 'automation',
    minRole: 'user',
    description: 'GitHub repo watcher: Pantau release/PR repo GitHub.',
    usage: '/githubwatch',
    examples: ['/githubwatch']
  },
  {
    id: 'F105',
    name: 'rsswatcher',
    aliases: ['f105'],
    category: 'general',
    plugin: 'automation',
    featureFlag: 'automation',
    minRole: 'admin',
    description: 'RSS watcher: Kirim update RSS ke grup.',
    usage: '/rsswatcher',
    examples: ['/rsswatcher']
  },
  {
    id: 'F106',
    name: 'formcollector',
    aliases: ['f106'],
    category: 'general',
    plugin: 'automation',
    featureFlag: 'automation',
    minRole: 'user',
    description: 'Form collector: Kumpulkan input dari member.',
    usage: '/formcollector',
    examples: ['/formcollector']
  },
  {
    id: 'F107',
    name: 'autolabel',
    aliases: ['f107'],
    category: 'general',
    plugin: 'automation',
    featureFlag: 'automation',
    minRole: 'admin',
    description: 'Auto-label pesan: Melabeli pesan penting secara otomatis.',
    usage: '/autolabel',
    examples: ['/autolabel']
  },
  {
    id: 'F108',
    name: 'commandmacro',
    aliases: ['f108'],
    category: 'general',
    plugin: 'automation',
    featureFlag: 'automation',
    minRole: 'admin',
    description: 'Command macro: Menjalankan beberapa command beruntun.',
    usage: '/commandmacro',
    examples: ['/commandmacro']
  },
  {
    id: 'F109',
    name: 'scheduledcmd',
    aliases: ['f109'],
    category: 'general',
    plugin: 'automation',
    featureFlag: 'automation',
    minRole: 'admin',
    description: 'Scheduled command: Menjalankan command secara terjadwal.',
    usage: '/scheduledcmd',
    examples: ['/scheduledcmd']
  },
  {
    id: 'F110',
    name: 'integrationhealth',
    aliases: ['f110'],
    category: 'general',
    plugin: 'automation',
    featureFlag: 'automation',
    minRole: 'admin',
    description: 'Integration health check: Periksa status API eksternal.',
    usage: '/integrationhealth',
    examples: ['/integrationhealth']
  },

  // 7.12. Analytics, Dashboard & Insight (F111-F120)
  {
    id: 'F111',
    name: 'dashboardheatmap',
    aliases: ['f111'],
    category: 'general',
    plugin: 'analytics',
    featureFlag: 'analytics',
    minRole: 'admin',
    description: 'Dashboard command heatmap: Peta waktu ramai command grup.',
    usage: '/dashboardheatmap',
    examples: ['/dashboardheatmap']
  },
  {
    id: 'F112',
    name: 'featureadoption',
    aliases: ['f112'],
    category: 'general',
    plugin: 'analytics',
    featureFlag: 'analytics',
    minRole: 'admin',
    description: 'Feature adoption report: Laporan fitur yang jarang dipakai.',
    usage: '/featureadoption',
    examples: ['/featureadoption']
  },
  {
    id: 'F113',
    name: 'tophelper',
    aliases: ['f113'],
    category: 'general',
    plugin: 'analytics',
    featureFlag: 'analytics',
    minRole: 'user',
    description: 'Top helper leaderboard: Ranking member paling membantu.',
    usage: '/tophelper',
    examples: ['/tophelper']
  },
  {
    id: 'F114',
    name: 'moderationtrend',
    aliases: ['f114'],
    category: 'general',
    plugin: 'analytics',
    featureFlag: 'analytics',
    minRole: 'admin',
    description: 'Moderation trend: Grafik tren spam, badword, dan warning.',
    usage: '/moderationtrend',
    examples: ['/moderationtrend']
  },
  {
    id: 'F115',
    name: 'gameengagement',
    aliases: ['f115'],
    category: 'general',
    plugin: 'analytics',
    featureFlag: 'analytics',
    minRole: 'user',
    description: 'Game engagement report: Win rate dan session length game.',
    usage: '/gameengagement',
    examples: ['/gameengagement']
  },
  {
    id: 'F116',
    name: 'aicostreport',
    aliases: ['f116'],
    category: 'general',
    plugin: 'analytics',
    featureFlag: 'analytics',
    minRole: 'admin',
    description: 'AI usage cost report: Estimasi biaya token AI.',
    usage: '/aicostreport',
    examples: ['/aicostreport']
  },
  {
    id: 'F117',
    name: 'errorfingerprint',
    aliases: ['f117'],
    category: 'general',
    plugin: 'analytics',
    featureFlag: 'analytics',
    minRole: 'admin',
    description: 'Error fingerprinting: Pengelompokan error runtime serupa.',
    usage: '/errorfingerprint',
    examples: ['/errorfingerprint']
  },
  {
    id: 'F118',
    name: 'slowcmdtracing',
    aliases: ['f118'],
    category: 'general',
    plugin: 'analytics',
    featureFlag: 'analytics',
    minRole: 'admin',
    description: 'Slow command tracing: Catat command yang lambat merespon.',
    usage: '/slowcmdtracing',
    examples: ['/slowcmdtracing']
  },
  {
    id: 'F119',
    name: 'adminaudit',
    aliases: ['f119'],
    category: 'general',
    plugin: 'analytics',
    featureFlag: 'analytics',
    minRole: 'admin',
    description: 'Admin action audit: Log audit pergantian setelan grup.',
    usage: '/adminaudit',
    examples: ['/adminaudit']
  },
  {
    id: 'F120',
    name: 'weeklyreport',
    aliases: ['f120'],
    category: 'general',
    plugin: 'analytics',
    featureFlag: 'analytics',
    minRole: 'owner',
    description: 'Weekly owner report: Ringkasan mingguan bot ke owner.',
    usage: '/weeklyreport',
    examples: ['/weeklyreport']
  },

  // 7.13. Reliability, DevOps & Developer Experience (F121-F130)
  {
    id: 'F121',
    name: 'pluginlazyload',
    aliases: ['f121'],
    category: 'owner',
    plugin: 'developer',
    featureFlag: 'developer',
    minRole: 'owner',
    description: 'Plugin lazy loading: Loader command dinamis.',
    usage: '/pluginlazyload',
    examples: ['/pluginlazyload']
  },
  {
    id: 'F122',
    name: 'pluginsandbox',
    aliases: ['f122'],
    category: 'owner',
    plugin: 'developer',
    featureFlag: 'developer',
    minRole: 'owner',
    description: 'Plugin sandbox contract: Metadata dan validasi sandbox.',
    usage: '/pluginsandbox',
    examples: ['/pluginsandbox']
  },
  {
    id: 'F123',
    name: 'migrationguard',
    aliases: ['f123'],
    category: 'owner',
    plugin: 'developer',
    featureFlag: 'developer',
    minRole: 'owner',
    description: 'Migration guard: Backup otomatis sebelum migrasi DB.',
    usage: '/migrationguard',
    examples: ['/migrationguard']
  },
  {
    id: 'F124',
    name: 'postgresprofile',
    aliases: ['f124'],
    category: 'owner',
    plugin: 'developer',
    featureFlag: 'developer',
    minRole: 'owner',
    description: 'PostgreSQL production profile: Monitoring koneksi PostgreSQL.',
    usage: '/postgresprofile',
    examples: ['/postgresprofile']
  },
  {
    id: 'F125',
    name: 'structuredlogging',
    aliases: ['f125'],
    category: 'owner',
    plugin: 'developer',
    featureFlag: 'developer',
    minRole: 'owner',
    description: 'Structured logging: Sensor redaction pada JSON logging.',
    usage: '/structuredlogging',
    examples: ['/structuredlogging']
  },
  {
    id: 'F126',
    name: 'gracefulshutdown',
    aliases: ['f126'],
    category: 'owner',
    plugin: 'developer',
    featureFlag: 'developer',
    minRole: 'owner',
    description: 'Graceful shutdown: Menutup koneksi/DB aman saat stop.',
    usage: '/gracefulshutdown',
    examples: ['/gracefulshutdown']
  },
  {
    id: 'F127',
    name: 'jobidempotency',
    aliases: ['f127'],
    category: 'owner',
    plugin: 'developer',
    featureFlag: 'developer',
    minRole: 'owner',
    description: 'Job idempotency: Menghindari pemrosesan job ganda.',
    usage: '/jobidempotency',
    examples: ['/jobidempotency']
  },
  {
    id: 'F128',
    name: 'healthcheckdetail',
    aliases: ['f128'],
    category: 'owner',
    plugin: 'developer',
    featureFlag: 'developer',
    minRole: 'owner',
    description: 'Healthcheck detail: Liveness check database/Redis/queue.',
    usage: '/healthcheckdetail',
    examples: ['/healthcheckdetail']
  },
  {
    id: 'F129',
    name: 'testfixture',
    aliases: ['f129'],
    category: 'owner',
    plugin: 'developer',
    featureFlag: 'developer',
    minRole: 'owner',
    description: 'Test fixture bot: Simulasi chat adaptor di testing.',
    usage: '/testfixture',
    examples: ['/testfixture']
  },
  {
    id: 'F130',
    name: 'docsgenerator',
    aliases: ['f130'],
    category: 'owner',
    plugin: 'developer',
    featureFlag: 'developer',
    minRole: 'owner',
    description: 'Command docs generator v2: Pembuatan dokumen otomatis.',
    usage: '/docsgenerator',
    examples: ['/docsgenerator']
  },

  // 7.14. Monetisasi, Premium & Pengalaman User (F131-F140)
  {
    id: 'F131',
    name: 'planmatrix',
    aliases: ['f131'],
    category: 'owner',
    plugin: 'premium',
    featureFlag: 'premium',
    minRole: 'owner',
    description: 'Plan entitlement matrix: Pengaturan tier free/premium.',
    usage: '/planmatrix',
    examples: ['/planmatrix']
  },
  {
    id: 'F132',
    name: 'trialotomatis',
    aliases: ['f132'],
    category: 'owner',
    plugin: 'premium',
    featureFlag: 'premium',
    minRole: 'owner',
    description: 'Trial otomatis: Konfigurasi trial premium berwaktu.',
    usage: '/trialotomatis',
    examples: ['/trialotomatis']
  },
  {
    id: 'F133',
    name: 'couponsystem',
    aliases: ['f133'],
    category: 'owner',
    plugin: 'premium',
    featureFlag: 'premium',
    minRole: 'owner',
    description: 'Coupon system v2: Pembuatan kupon promo diskon.',
    usage: '/couponsystem',
    examples: ['/couponsystem']
  },
  {
    id: 'F134',
    name: 'usagequota',
    aliases: ['f134'],
    category: 'owner',
    plugin: 'premium',
    featureFlag: 'premium',
    minRole: 'owner',
    description: 'Usage quota wallet: Pengecekan saldo kuota pemakaian.',
    usage: '/usagequota',
    examples: ['/usagequota']
  },
  {
    id: 'F135',
    name: 'premiumonboarding',
    aliases: ['f135'],
    category: 'owner',
    plugin: 'premium',
    featureFlag: 'premium',
    minRole: 'owner',
    description: 'Premium onboarding: Panduan setelah aktivasi premium.',
    usage: '/premiumonboarding',
    examples: ['/premiumonboarding']
  },
  {
    id: 'F136',
    name: 'paymentproof',
    aliases: ['f136'],
    category: 'owner',
    plugin: 'premium',
    featureFlag: 'premium',
    minRole: 'owner',
    description: 'Payment proof workflow: Verifikasi bukti bayar.',
    usage: '/paymentproof',
    examples: ['/paymentproof']
  },
  {
    id: 'F137',
    name: 'renewalreminder',
    aliases: ['f137'],
    category: 'owner',
    plugin: 'premium',
    featureFlag: 'premium',
    minRole: 'owner',
    description: 'Renewal reminder: Notifikasi perpanjangan sewa.',
    usage: '/renewalreminder',
    examples: ['/renewalreminder']
  },
  {
    id: 'F138',
    name: 'referralreward',
    aliases: ['f138'],
    category: 'owner',
    plugin: 'premium',
    featureFlag: 'premium',
    minRole: 'owner',
    description: 'Referral reward: Klaim bonus mengajak pengguna baru.',
    usage: '/referralreward',
    examples: ['/referralreward']
  },
  {
    id: 'F139',
    name: 'featureteaser',
    aliases: ['f139'],
    category: 'owner',
    plugin: 'premium',
    featureFlag: 'premium',
    minRole: 'owner',
    description: 'Feature teaser: Pembatasan demo fitur premium.',
    usage: '/featureteaser',
    examples: ['/featureteaser']
  },
  {
    id: 'F140',
    name: 'satisfactionsurvey',
    aliases: ['f140'],
    category: 'owner',
    plugin: 'premium',
    featureFlag: 'premium',
    minRole: 'owner',
    description: 'Satisfaction survey: Survey umpan balik pengguna.',
    usage: '/satisfactionsurvey',
    examples: ['/satisfactionsurvey']
  },

  // 8. Scope Game Baru — 50 Game Tambahan (G001-G050)
  {
    id: 'G001',
    name: 'wwchaos',
    aliases: ['g001'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Werewolf Chaos Mode: Varian Werewolf dengan modifier ronde.',
    usage: '/wwchaos',
    examples: ['/wwchaos']
  },
  {
    id: 'G002',
    name: 'wwranked',
    aliases: ['g002'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Werewolf Ranked Season: Mode MMR werewolf musiman.',
    usage: '/wwranked',
    examples: ['/wwranked']
  },
  {
    id: 'G003',
    name: 'mafiasch',
    aliases: ['g003'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Mafia Sekolah: Social deduction bertema sekolah.',
    usage: '/mafiasch',
    examples: ['/mafiasch']
  },
  {
    id: 'G004',
    name: 'detective',
    aliases: ['g004'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Detective Case: Menebak pelaku berdasarkan clue bertahap.',
    usage: '/detective',
    examples: ['/detective']
  },
  {
    id: 'G005',
    name: 'escape',
    aliases: ['g005'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Escape Room Grup: Puzzle berantai memecahkan sandi.',
    usage: '/escape',
    examples: ['/escape']
  },
  {
    id: 'G006',
    name: 'treasure',
    aliases: ['g006'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Treasure Hunt: Clue lokasi virtual rahasia.',
    usage: '/treasure',
    examples: ['/treasure']
  },
  {
    id: 'G007',
    name: 'kataberantai',
    aliases: ['g007'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Kata Berantai Battle: Sambung kata dengan timer eliminasi.',
    usage: '/kataberantai',
    examples: ['/kataberantai']
  },
  {
    id: 'G008',
    name: 'tebakemoji',
    aliases: ['g008'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Tebak Emoji Cerita: Tebak peribahasa/film dari emoji.',
    usage: '/tebakemoji',
    examples: ['/tebakemoji']
  },
  {
    id: 'G009',
    name: 'tebaksuara',
    aliases: ['g009'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Tebak Suara: Tebak file suara/audio pendek.',
    usage: '/tebaksuara',
    examples: ['/tebaksuara']
  },
  {
    id: 'G010',
    name: 'tebaksiluet',
    aliases: ['g010'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Tebak Siluet: Tebak gambar dengan siluet bertahap.',
    usage: '/tebaksiluet',
    examples: ['/tebaksiluet']
  },
  {
    id: 'G011',
    name: 'quizduel',
    aliases: ['g011'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Quiz Duel 1v1: Adu kecepatan menjawab kuis pvp.',
    usage: '/quizduel',
    examples: ['/quizduel']
  },
  {
    id: 'G012',
    name: 'quizbattleroyale',
    aliases: ['g012'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Quiz Battle Royale: Adu kuis bertahan hidup massal.',
    usage: '/quizbattleroyale',
    examples: ['/quizbattleroyale']
  },
  {
    id: 'G013',
    name: 'rankingcepat',
    aliases: ['g013'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Ranking Cepat: Urutkan data/angka/tahun terakurat.',
    usage: '/rankingcepat',
    examples: ['/rankingcepat']
  },
  {
    id: 'G014',
    name: 'family100league',
    aliases: ['g014'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Family 100 League: Liga Family100 berbank data.',
    usage: '/family100league',
    examples: ['/family100league']
  },
  {
    id: 'G015',
    name: 'surveysays',
    aliases: ['g015'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Survey Says Indonesia: Family100 kustom lokal.',
    usage: '/surveysays',
    examples: ['/surveysays']
  },
  {
    id: 'G016',
    name: 'mathsprint',
    aliases: ['g016'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Math Sprint: Kuis matematika ber-streak 60 detik.',
    usage: '/mathsprint',
    examples: ['/mathsprint']
  },
  {
    id: 'G017',
    name: 'mathboss',
    aliases: ['g017'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Math Boss: Serang boss dengan jawaban matematika.',
    usage: '/mathboss',
    examples: ['/mathboss']
  },
  {
    id: 'G018',
    name: 'puzzle24',
    aliases: ['g018'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Puzzle Angka 24: Operasikan 4 angka menghasilkan 24.',
    usage: '/puzzle24',
    examples: ['/puzzle24']
  },
  {
    id: 'G019',
    name: 'sudokumini',
    aliases: ['g019'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Sudoku Mini: Game Sudoku grid mini 4x4.',
    usage: '/sudokumini',
    examples: ['/sudokumini']
  },
  {
    id: 'G020',
    name: 'wordleindo',
    aliases: ['g020'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Wordle Indonesia: Tebak kata 5 huruf.',
    usage: '/wordleindo',
    examples: ['/wordleindo']
  },
  {
    id: 'G021',
    name: 'hangmanindo',
    aliases: ['g021'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Hangman Indonesia: Tebak kata bermodul nyawa.',
    usage: '/hangmanindo',
    examples: ['/hangmanindo']
  },
  {
    id: 'G022',
    name: 'anagramrace',
    aliases: ['g022'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Anagram Race: Menyusun ulang acakan huruf.',
    usage: '/anagramrace',
    examples: ['/anagramrace']
  },
  {
    id: 'G023',
    name: 'typingrace',
    aliases: ['g023'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Typing Race: Lomba ketik cepat kalimat.',
    usage: '/typingrace',
    examples: ['/typingrace']
  },
  {
    id: 'G024',
    name: 'memorycards',
    aliases: ['g024'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Memory Cards: Mencocokkan kartu via koordinat.',
    usage: '/memorycards',
    examples: ['/memorycards']
  },
  {
    id: 'G025',
    name: 'minesweeperchat',
    aliases: ['g025'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Minesweeper Chat: Sapu ranjau berbasis grid chat.',
    usage: '/minesweeperchat',
    examples: ['/minesweeperchat']
  },
  {
    id: 'G026',
    name: 'tictactoeultimate',
    aliases: ['g026'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'TicTacToe Ultimate: TTT format turnamen 3 papan.',
    usage: '/tictactoeultimate',
    examples: ['/tictactoeultimate']
  },
  {
    id: 'G027',
    name: 'connectfour',
    aliases: ['g027'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Connect Four: Game menyusun 4 kolom berurutan.',
    usage: '/connectfour',
    examples: ['/connectfour']
  },
  {
    id: 'G028',
    name: 'battleship',
    aliases: ['g028'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Battleship Mini: Tebak koordinat kapal musuh.',
    usage: '/battleship',
    examples: ['/battleship']
  },
  {
    id: 'G029',
    name: 'caturmini',
    aliases: ['g029'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Catur Mini Puzzle: Puzzle mate-in-one catur.',
    usage: '/caturmini',
    examples: ['/caturmini']
  },
  {
    id: 'G030',
    name: 'suittournament',
    aliases: ['g030'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Suit Tournament: Turnamen suit bracket.',
    usage: '/suittournament',
    examples: ['/suittournament']
  },
  {
    id: 'G031',
    name: 'unolite',
    aliases: ['g031'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'UNO Lite: Permainan kartu warna/angka aksi.',
    usage: '/unolite',
    examples: ['/unolite']
  },
  {
    id: 'G032',
    name: 'blackjackedu',
    aliases: ['g032'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Blackjack Edu: Belajar hitung kartu virtual.',
    usage: '/blackjackedu',
    examples: ['/blackjackedu']
  },
  {
    id: 'G033',
    name: 'monopolymini',
    aliases: ['g033'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Monopoly Mini: Beli petak dan sewa fiktif.',
    usage: '/monopolymini',
    examples: ['/monopolymini']
  },
  {
    id: 'G034',
    name: 'markettycoon',
    aliases: ['g034'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Market Tycoon: Simulasi bisnis jual beli fiktif.',
    usage: '/markettycoon',
    examples: ['/markettycoon']
  },
  {
    id: 'G035',
    name: 'farmrpg',
    aliases: ['g035'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Farm RPG: Tanam dan panen virtual.',
    usage: '/farmrpg',
    examples: ['/farmrpg']
  },
  {
    id: 'G036',
    name: 'fishingtournament',
    aliases: ['g036'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Fishing Tournament: Turnamen mancing cuaca real-time.',
    usage: '/fishingtournament',
    examples: ['/fishingtournament']
  },
  {
    id: 'G037',
    name: 'dungeonparty',
    aliases: ['g037'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Dungeon Party: RPG dungeon co-op dengan role.',
    usage: '/dungeonparty',
    examples: ['/dungeonparty']
  },
  {
    id: 'G038',
    name: 'petbattle',
    aliases: ['g038'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Pet Battle: Duel pet peliharaan naik level.',
    usage: '/petbattle',
    examples: ['/petbattle']
  },
  {
    id: 'G039',
    name: 'guildwar',
    aliases: ['g039'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Guild War: Kumpulkan poin quest kelompok.',
    usage: '/guildwar',
    examples: ['/guildwar']
  },
  {
    id: 'G040',
    name: 'dailyquestboard',
    aliases: ['g040'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Daily Quest Board: Misi harian klaim XP/koin.',
    usage: '/dailyquestboard',
    examples: ['/dailyquestboard']
  },
  {
    id: 'G041',
    name: 'truthordarestory',
    aliases: ['g041'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Truth or Dare Story: TOD bertema level ber-vote.',
    usage: '/truthordarestory',
    examples: ['/truthordarestory']
  },
  {
    id: 'G042',
    name: 'confessionmystery',
    aliases: ['g042'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Confession Mystery: Menebak pengirim pesan anonim.',
    usage: '/confessionmystery',
    examples: ['/confessionmystery']
  },
  {
    id: 'G043',
    name: 'impostorword',
    aliases: ['g043'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Impostor Word: Cari penyusup kata tersembunyi.',
    usage: '/impostorword',
    examples: ['/impostorword']
  },
  {
    id: 'G044',
    name: 'spyfall',
    aliases: ['g044'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Spyfall Chat: Tanya jawab temukan mata-mata.',
    usage: '/spyfall',
    examples: ['/spyfall']
  },
  {
    id: 'G045',
    name: 'siapaaku',
    aliases: ['g045'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Siapa Aku?: Tebak karakter ya/tidak.',
    usage: '/siapaaku',
    examples: ['/siapaaku']
  },
  {
    id: 'G046',
    name: 'debatearena',
    aliases: ['g046'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Debate Arena: Voting penentu debat terseru.',
    usage: '/debatearena',
    examples: ['/debatearena']
  },
  {
    id: 'G047',
    name: 'captioncontest',
    aliases: ['g047'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Caption Contest: Lomba buat caption tergokil.',
    usage: '/captioncontest',
    examples: ['/captioncontest']
  },
  {
    id: 'G048',
    name: 'memewar',
    aliases: ['g048'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Meme War: Lomba meme bertema.',
    usage: '/memewar',
    examples: ['/memewar']
  },
  {
    id: 'G049',
    name: 'storychain',
    aliases: ['g049'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Story Chain: Sambung cerita dengan twist.',
    usage: '/storychain',
    examples: ['/storychain']
  },
  {
    id: 'G050',
    name: 'lelangcepat',
    aliases: ['g050'],
    category: 'games',
    plugin: 'games',
    featureFlag: 'games',
    minRole: 'user',
    description: 'Lelang Cepat: Lelang barang fiktif dengan saldo koin.',
    usage: '/lelangcepat',
    examples: ['/lelangcepat']
  }
];
